"""add composed_text and validator_version to agent_rationales for scrum_53

Revision ID: b35e4801d1e1
Revises: d6b18edd9aef
Create Date: 2026-09-29 12:16:03.393326

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b35e4801d1e1'
down_revision: str | Sequence[str] | None = 'd6b18edd9aef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_rationales', sa.Column('composed_text', sa.String(), nullable=True))
    op.add_column('agent_rationales', sa.Column('validator_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_rationales', 'validator_version')
    op.drop_column('agent_rationales', 'composed_text')
    # ### end Alembic commands ###
