"""add transaction_flags table for SCRUM-61

Revision ID: b8f1285c79c7
Revises: 23efdf64f3d5
Create Date: 2026-09-08 08:56:33.784960

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b8f1285c79c7'
down_revision: str | Sequence[str] | None = '23efdf64f3d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'rule_name', name='uq_transaction_flags_transaction_rule')
    )
    op.create_index('ix_transaction_flags_transaction_id', 'transaction_flags', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_flags_transaction_id', table_name='transaction_flags')
    op.drop_table('transaction_flags')
    # ### end Alembic commands ###
