"""add agent_rationales table for scrum_53

Revision ID: d6b18edd9aef
Revises: b8f1285c79c7
Create Date: 2026-09-29 11:24:45.825384

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6b18edd9aef'
down_revision: str | Sequence[str] | None = 'b8f1285c79c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_rationales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('fact_fingerprint', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=False),
    sa.Column('composition_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_rationales_transaction_fingerprint_prompt_version', 'agent_rationales', ['transaction_id', 'fact_fingerprint', 'prompt_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_rationales_transaction_fingerprint_prompt_version', table_name='agent_rationales')
    op.drop_table('agent_rationales')
    # ### end Alembic commands ###
